# Generated by Django 4.1.5 on 2023-01-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='p',
            new_name='name',
        ),
    ]
