# Generated by Django 4.1.5 on 2023-02-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_couser_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
