# Generated by Django 4.1.5 on 2023-02-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_comment_lesson_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
